//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataModelEdmx
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DropBoxEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DropBoxEntities object using the connection string found in the 'DropBoxEntities' section of the application configuration file.
        /// </summary>
        public DropBoxEntities() : base("name=DropBoxEntities", "DropBoxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DropBoxEntities object.
        /// </summary>
        public DropBoxEntities(string connectionString) : base(connectionString, "DropBoxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DropBoxEntities object.
        /// </summary>
        public DropBoxEntities(EntityConnection connection) : base(connection, "DropBoxEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DropBoxUser> DropBoxUsers
        {
            get
            {
                if ((_DropBoxUsers == null))
                {
                    _DropBoxUsers = base.CreateObjectSet<DropBoxUser>("DropBoxUsers");
                }
                return _DropBoxUsers;
            }
        }
        private ObjectSet<DropBoxUser> _DropBoxUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AxactToDropBoxMapping> AxactToDropBoxMappings
        {
            get
            {
                if ((_AxactToDropBoxMappings == null))
                {
                    _AxactToDropBoxMappings = base.CreateObjectSet<AxactToDropBoxMapping>("AxactToDropBoxMappings");
                }
                return _AxactToDropBoxMappings;
            }
        }
        private ObjectSet<AxactToDropBoxMapping> _AxactToDropBoxMappings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DropBoxUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDropBoxUsers(DropBoxUser dropBoxUser)
        {
            base.AddObject("DropBoxUsers", dropBoxUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AxactToDropBoxMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAxactToDropBoxMappings(AxactToDropBoxMapping axactToDropBoxMapping)
        {
            base.AddObject("AxactToDropBoxMappings", axactToDropBoxMapping);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DropBoxModel", Name="AxactToDropBoxMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AxactToDropBoxMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AxactToDropBoxMapping object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="axactDocumentID">Initial value of the AxactDocumentID property.</param>
        /// <param name="dropBoxRev">Initial value of the DropBoxRev property.</param>
        /// <param name="dropBoxPath">Initial value of the DropBoxPath property.</param>
        public static AxactToDropBoxMapping CreateAxactToDropBoxMapping(global::System.Guid id, global::System.Guid axactDocumentID, global::System.String dropBoxRev, global::System.String dropBoxPath)
        {
            AxactToDropBoxMapping axactToDropBoxMapping = new AxactToDropBoxMapping();
            axactToDropBoxMapping.ID = id;
            axactToDropBoxMapping.AxactDocumentID = axactDocumentID;
            axactToDropBoxMapping.DropBoxRev = dropBoxRev;
            axactToDropBoxMapping.DropBoxPath = dropBoxPath;
            return axactToDropBoxMapping;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, "UserID");
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AxactDocumentID
        {
            get
            {
                return _AxactDocumentID;
            }
            set
            {
                OnAxactDocumentIDChanging(value);
                ReportPropertyChanging("AxactDocumentID");
                _AxactDocumentID = StructuralObject.SetValidValue(value, "AxactDocumentID");
                ReportPropertyChanged("AxactDocumentID");
                OnAxactDocumentIDChanged();
            }
        }
        private global::System.Guid _AxactDocumentID;
        partial void OnAxactDocumentIDChanging(global::System.Guid value);
        partial void OnAxactDocumentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DropBoxRev
        {
            get
            {
                return _DropBoxRev;
            }
            set
            {
                OnDropBoxRevChanging(value);
                ReportPropertyChanging("DropBoxRev");
                _DropBoxRev = StructuralObject.SetValidValue(value, false, "DropBoxRev");
                ReportPropertyChanged("DropBoxRev");
                OnDropBoxRevChanged();
            }
        }
        private global::System.String _DropBoxRev;
        partial void OnDropBoxRevChanging(global::System.String value);
        partial void OnDropBoxRevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DropBoxPath
        {
            get
            {
                return _DropBoxPath;
            }
            set
            {
                OnDropBoxPathChanging(value);
                ReportPropertyChanging("DropBoxPath");
                _DropBoxPath = StructuralObject.SetValidValue(value, false, "DropBoxPath");
                ReportPropertyChanged("DropBoxPath");
                OnDropBoxPathChanged();
            }
        }
        private global::System.String _DropBoxPath;
        partial void OnDropBoxPathChanging(global::System.String value);
        partial void OnDropBoxPathChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DropBoxModel", Name="DropBoxUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DropBoxUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DropBoxUser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        /// <param name="secret">Initial value of the Secret property.</param>
        /// <param name="isAccessToken">Initial value of the IsAccessToken property.</param>
        public static DropBoxUser CreateDropBoxUser(global::System.Guid userID, global::System.String token, global::System.String secret, global::System.Boolean isAccessToken)
        {
            DropBoxUser dropBoxUser = new DropBoxUser();
            dropBoxUser.UserID = userID;
            dropBoxUser.Token = token;
            dropBoxUser.Secret = secret;
            dropBoxUser.IsAccessToken = isAccessToken;
            return dropBoxUser;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, "UserID");
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false, "Token");
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Secret
        {
            get
            {
                return _Secret;
            }
            set
            {
                OnSecretChanging(value);
                ReportPropertyChanging("Secret");
                _Secret = StructuralObject.SetValidValue(value, false, "Secret");
                ReportPropertyChanged("Secret");
                OnSecretChanged();
            }
        }
        private global::System.String _Secret;
        partial void OnSecretChanging(global::System.String value);
        partial void OnSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAccessToken
        {
            get
            {
                return _IsAccessToken;
            }
            set
            {
                OnIsAccessTokenChanging(value);
                ReportPropertyChanging("IsAccessToken");
                _IsAccessToken = StructuralObject.SetValidValue(value, "IsAccessToken");
                ReportPropertyChanged("IsAccessToken");
                OnIsAccessTokenChanged();
            }
        }
        private global::System.Boolean _IsAccessToken;
        partial void OnIsAccessTokenChanging(global::System.Boolean value);
        partial void OnIsAccessTokenChanged();

        #endregion

    }

    #endregion

}
